config/routes.rb
Comparamercados::Application.routes.draw do
  resources :productos

  resources :supermercados

  root 'public#index'

  controller :public do
    get "producto/:id" => :ver_producto
    post "producto/:id" => :agregar_producto, as: "agregar_producto"
    get "compara_productos" => :comparador, as: "comparador"
  end

end

app/models/producto.rb
class Producto < ActiveRecord::Base
	belongs_to :supermercado
	mount_uploader :imagen, ImagenUploader
end

app/models/supermercado.rb
class Supermercado < ActiveRecord::Base
	has_many :productos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @producto }
      else
        format.html { render action: 'new' }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:imagen, :descripcion, :precio, :supermercado_id)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

	def index
		unless params[:busqueda].blank?
			@productos = Producto.where("descripcion LIKE :busqueda", {busqueda: "%#{params[:busqueda]}%"})
		else
			@productos = Producto.find(:all).sample(5)
		end
	end

	def ver_producto
		producto_id = params[:id]
  	@producto = Producto.find producto_id
	end

	def agregar_producto

		if cookies[:id].nil?
			cookies[:id] = params[:id]
		else
			cookies[:id] = cookies[:id].split << params[:id]
		end
		
		redirect_to root_path
	end

	def comparador
		if cookies[:id].nil?
			redirect_to root_path
		else
			@productos = Producto.find cookies[:id].split('&')
		end
	end
end

app/controllers/supermercados_controller.rb
class SupermercadosController < ApplicationController
  before_action :set_supermercado, only: [:show, :edit, :update, :destroy]

  # GET /supermercados
  # GET /supermercados.json
  def index
    @supermercados = Supermercado.all
  end

  # GET /supermercados/1
  # GET /supermercados/1.json
  def show
  end

  # GET /supermercados/new
  def new
    @supermercado = Supermercado.new
  end

  # GET /supermercados/1/edit
  def edit
  end

  # POST /supermercados
  # POST /supermercados.json
  def create
    @supermercado = Supermercado.new(supermercado_params)

    respond_to do |format|
      if @supermercado.save
        format.html { redirect_to @supermercado, notice: 'Supermercado was successfully created.' }
        format.json { render action: 'show', status: :created, location: @supermercado }
      else
        format.html { render action: 'new' }
        format.json { render json: @supermercado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supermercados/1
  # PATCH/PUT /supermercados/1.json
  def update
    respond_to do |format|
      if @supermercado.update(supermercado_params)
        format.html { redirect_to @supermercado, notice: 'Supermercado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @supermercado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supermercados/1
  # DELETE /supermercados/1.json
  def destroy
    @supermercado.destroy
    respond_to do |format|
      format.html { redirect_to supermercados_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supermercado
      @supermercado = Supermercado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supermercado_params
      params.require(:supermercado).permit(:logo, :nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/supermercados_helper.rb
module SupermercadosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>ComparaMercados</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<%= javascript_include_tag "application" %>
  	<div class="contain-to-grid">
      <nav id="menu_superior" class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name"></li>
          <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
        </ul>
        <section class="top-bar-section">
          <!-- Right Nav Section -->
            <ul class="right">
            	<li class="active"><a href="#">Inicio</a></li>
              <li>
                <%= link_to "Sobre nosotros", root_path %>
              </li>
            </ul>
        </section>
      </nav>
    </div>

    <br></br>

    <% unless cookies[:id].nil? %>
    	<div class="row">
	      <div class="large-12 small-12 columns text-center">
	        <div class="large-6 small-6 columns text-center">
				  	<div id="mensaje_productos" data-alert class="alert-box success radius">
				  		<h6>Productos agregados a comparador</h6>
				  		<% if cookies[:id].split('&').count == 1 %>
				  			<% producto = Producto.find cookies[:id] %>
				  			<h7><%= producto.descripcion %></h7>
				  		<% else %>
				  			<% productos = Producto.find cookies[:id].split('&') %>
				  			<% productos.each do |producto| %>
				  				<div class="clear"></div>
				  				<h7><%= producto.descripcion %></h7>
				  				<div class="clear"></div>
				  			<% end %>
				  			<%= link_to "Compara!", comparador_path %>
				  		<% end %>
						  <a id="alert" href="#" class="close">&times;</a>
						</div>
					</div>
	      </div>
	    </div>
	  <% end %>

	  <br></br>

	  <section role="main">
	    <div class="row">
	      <div class="large-12 small-12 columns text-center">
	        <%#= link_to root_path, id: 'link_logo' do %>
	          <%#= image_tag "logo.png", id: 'logo' %>
	        <%# end %>

	    		<%= yield %>

	      </div>
	    </div>
	    <br></br>
	    <br></br>
	    <br></br>
		  <div id="footer" class="row">
		    <div id="contenido_footer" class="large-12 small-12 columns">
		      <div id="redes_sociales">
		        <!-- <h4>Siguenos en </h4>
		        <a href="https://github.com/DiegoRodriguezG/ComparaMercados" target="_blank">
		        </a> -->
		      </div>
		    </div>
		  </div>
	  </section>

	  <script type="text/javascript">
	  	$(function() {
        $("#alert").click(function(){
        	$.removeCookie("id");
        });
      });
	  </script>
  </body>
</html>

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :imagen %><br>
    <%= f.text_field :imagen %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio %>
  </div>
  <div class="field">
    <%= f.label :supermercado_id %><br>
    <%= f.number_field :supermercado_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<h1>Listing productos</h1>

<table>
  <thead>
    <tr>
      <th>Imagen</th>
      <th>Descripcion</th>
      <th>Precio</th>
      <th>Supermercado</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= image_tag producto.imagen %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.supermercado_id %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Imagen:</strong>
  <%= image_tag @producto.imagen %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<p>
  <strong>Supermercado:</strong>
  <%= @producto.supermercado_id %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>

app/views/supermercados/_form.html.erb
<%= form_for(@supermercado) do |f| %>
  <% if @supermercado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supermercado.errors.count, "error") %> prohibited this supermercado from being saved:</h2>

      <ul>
      <% @supermercado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/supermercados/edit.html.erb
<h1>Editing supermercado</h1>

<%= render 'form' %>

<%= link_to 'Show', @supermercado %> |
<%= link_to 'Back', supermercados_path %>

app/views/supermercados/index.html.erb
<h1>Listing supermercados</h1>

<table>
  <thead>
    <tr>
      <th>Logo</th>
      <th>Nombre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @supermercados.each do |supermercado| %>
      <tr>
        <td><%= supermercado.logo %></td>
        <td><%= supermercado.nombre %></td>
        <td><%= link_to 'Show', supermercado %></td>
        <td><%= link_to 'Edit', edit_supermercado_path(supermercado) %></td>
        <td><%= link_to 'Destroy', supermercado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supermercado', new_supermercado_path %>

app/views/supermercados/new.html.erb
<h1>New supermercado</h1>

<%= render 'form' %>

<%= link_to 'Back', supermercados_path %>

app/views/supermercados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Logo:</strong>
  <%= @supermercado.logo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @supermercado.nombre %>
</p>

<%= link_to 'Edit', edit_supermercado_path(@supermercado) %> |
<%= link_to 'Back', supermercados_path %>